import type { Size } from "../../types";

type IconName =
  | "sun"
  | "moon"
  | "github"
  | "youtube"
  | "instagram"
  | "linkedIn"
  | "maximize"
  | "plus"
  | "close"
  | "check"
  | "asterisk"
  | "contrast"
  | "heart"
  | "whatsapp"
  | "activity"
  | "alert-circle"
  | "archive"
  | "alert-triangle"
  | "arrow-up-circle"
  | "arrow-down-circle"
  | "arrow-left-circle"
  | "arrow-right-circle"
  | "arrow-up"
  | "arrow-down"
  | "arrow-left"
  | "arrow-right"
  | "chevron-up"
  | "chevron-down"
  | "chevron-left"
  | "chevron-right"
  | "chevrons-up"
  | "chevrons-down"
  | "chevrons-left"
  | "chevrons-right"
  | "battery-charging"
  | "battery"
  | "airplay"
  | "corner-left-up"
  | "corner-right-up"
  | "corner-left-down"
  | "corner-right-down"
  | "corner-down-left"
  | "corner-up-left"
  | "corner-down-right"
  | "corner-up-right"
  | "bar-chart-2"
  | "bar-chart"
  | "calendar"
  | "box"
  | "aperture"
  | "at-sign"
  | "award"
  | "camera-off"
  | "camera"
  | "cast"
  | "check"
  | "close"
  | "bell-off"
  | "bell"
  | "bluetooth"
  | "droplet"
  | "book"
  | "bookmark"
  | "chrome"
  | "circle"
  | "clock"
  | "watch"
  | "cloud-drizzle"
  | "cloud-lightning"
  | "cloud-off"
  | "cloud"
  | "code"
  | "coffee"
  | "columns"
  | "command"
  | "compass"
  | "copy"
  | "cpu"
  | "credit-card"
  | "crop"
  | "crosshair"
  | "database"
  | "delete"
  | "download-cloud"
  | "download"
  | "rss"
  | "edit"
  | "external-link"
  | "eye-off"
  | "eye"
  | "fast-forward"
  | "figma"
  | "file-minus"
  | "file-text"
  | "folder"
  | "frown"
  | "gift"
  | "github"
  | "gitlab"
  | "globe"
  | "grid"
  | "headphones"
  | "heart"
  | "help-circle"
  | "home"
  | "image-1"
  | "info"
  | "link"
  | "link-2"
  | "layers"
  | "log-in"
  | "log-out"
  | "mail"
  | "map-pin"
  | "map"
  | "maximize-2"
  | "maximize"
  | "menu"
  | "message-square"
  | "mic-off"
  | "mic"
  | "minimize-2"
  | "monitor"
  | "moon"
  | "loader"
  | "sun"
  | "more-horizontal"
  | "more-vertical"
  | "disc"
  | "play-circle"
  | "pause-circle"
  | "play-circl-filled"
  | "pause-circle-filled"
  | "music"
  | "video-off"
  | "video"
  | "volume-x"
  | "volume"
  | "volume-1"
  | "volume-2"
  | "youtube"
  | "phone"
  | "tv"
  | "navigation-2"
  | "image-2"
  | "trash-2"
  | "trending-down"
  | "trending-up"
  | "pie-chart"
  | "plus"
  | "minus"
  | "search"
  | "unlock"
  | "power"
  | "save"
  | "rotate-ccw"
  | "rotate-cw"
  | "refresh-ccw"
  | "share"
  | "shopping-bag"
  | "sliders"
  | "star"
  | "stop-circle"
  | "tag"
  | "thumbs-down"
  | "thumbs-up"
  | "zap-off"
  | "zap"
  | "wifi"
  | "send"
  | "lunch"
  | "drinks"
  | "atm"
  | "user"
  | "users"
  | "qr-code"
  | "cab"
  | "google"
  | "facebook"
  | "twitter-fill"
  | "twitter-outline"
  | "dribbble"
  | "instagram"
  | "UPI"
  | "account"
  | "settings"
  | "lock"
  | "smile"
  | "user-plus"
  | "skip-back"
  | "skip-forward"
  | "shuffle"
  | "info-line"
  | "amazon-pay"
  | "paypal"
  | "snake"
  | "airplanemode-active"
  | "airplanemode-inactive"
  | "plus-circle";

interface IconAttrs extends Size {
  name: IconName;
  className?: string;
}

export const Icon = ({
  name,
  width = 24,
  height = width,
  className,
}: IconAttrs) => {
  return (
    <figure className={className}>
      <svg
        width={width}
        height={height}
        fill="none"
        viewBox="0 0 24 24"
        xmlns="http://www.w3.org/2000/svg"
      >
        <use href={"#" + name} />
      </svg>
    </figure>
  );
};
